# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/Vivado/PROJECTS/final assessment/CNN/CNNTeam3/project_1.cache/wt} [current_project]
set_property parent.project_path {F:/Vivado/PROJECTS/final assessment/CNN/CNNTeam3/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {F:/Vivado/PROJECTS/final assessment/CNN/CNNTeam3/project_1.srcs/sources_1/new/MUL.v}
  {F:/Vivado/PROJECTS/final assessment/CNN/CNNTeam3/project_1.srcs/sources_1/new/ADD.v}
  {F:/Vivado/PROJECTS/final assessment/CNN/CNNTeam3/project_1.srcs/sources_1/new/Conv_Basic.v}
}
synth_design -top Conv_Basic -part xc7z020clg400-1
write_checkpoint -noxdef Conv_Basic.dcp
catch { report_utilization -file Conv_Basic_utilization_synth.rpt -pb Conv_Basic_utilization_synth.pb }
